import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Generate individual student report card
export async function generateStudentReportCard(student: any, scores: any[]) {
  const doc = new jsPDF();

  // Header with school logo/name
  doc.setFontSize(22);
  doc.setTextColor(0, 51, 102);
  doc.text('IKONEX ACADEMY', 105, 25, { align: 'center' });

  doc.setFontSize(14);
  doc.setTextColor(100, 100, 100);
  doc.text('Student Report Card', 105, 38, { align: 'center' });

  doc.setDrawColor(0, 51, 102);
  doc.setLineWidth(1);
  doc.line(20, 45, 190, 45);

  // Student Information
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.text(`Name: ${student.name}`, 20, 58);
  doc.text(`Admission No: ${student.admissionNo}`, 20, 66);
  doc.text(`Class: ${student.stream?.name || 'N/A'}`, 20, 74);
  
  // Get term and year from first score or use defaults
  const term = scores[0]?.term || 'Term 1';
  const year = scores[0]?.year || new Date().getFullYear();
  doc.text(`Term: ${term}`, 140, 58);
  doc.text(`Year: ${year}`, 140, 66);

  // Scores Table
  const tableData = scores.map(score => [
    score.subject?.name || 'N/A',
    score.caScore.toString(),
    score.examScore.toString(),
    score.total.toString(),
    score.grade || '-',
    score.position ? `#${score.position}` : '-'
  ]);

  (doc as any).autoTable({
    startY: 85,
    head: [['Subject', 'CA Score', 'Exam Score', 'Total', 'Grade', 'Position']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [0, 51, 102], textColor: 255, fontSize: 10 },
    bodyStyles: { fontSize: 10 },
    columnStyles: {
      0: { cellWidth: 50 },
      1: { cellWidth: 20, align: 'center' },
      2: { cellWidth: 20, align: 'center' },
      3: { cellWidth: 20, align: 'center' },
      4: { cellWidth: 20, align: 'center' },
      5: { cellWidth: 25, align: 'center' }
    }
  });

  // Calculate summary statistics
  const finalY = (doc as any).lastAutoTable.finalY + 15;
  const totalMarks = scores.reduce((sum, s) => sum + s.total, 0);
  const average = scores.length > 0 ? totalMarks / scores.length : 0;
  
  // Determine overall grade
  let overallGrade = 'F';
  let remark = 'Fail';
  if (average >= 80) { overallGrade = 'A'; remark = 'Excellent'; }
  else if (average >= 70) { overallGrade = 'B'; remark = 'Very Good'; }
  else if (average >= 60) { overallGrade = 'C'; remark = 'Good'; }
  else if (average >= 50) { overallGrade = 'D'; remark = 'Pass'; }
  else if (average >= 40) { overallGrade = 'E'; remark = 'Below Average'; }

  // Summary section
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.text(`Total Marks: ${totalMarks}`, 20, finalY);
  doc.text(`Average Score: ${average.toFixed(2)}%`, 20, finalY + 8);
  doc.text(`Overall Grade: ${overallGrade}`, 20, finalY + 16);
  doc.text(`Remark: ${remark}`, 20, finalY + 24);

  // Subject performance breakdown
  const bestSubject = scores.reduce((best, s) => 
    s.total > (best?.total || 0) ? s : best, null);
  const worstSubject = scores.reduce((worst, s) => 
    s.total < (worst?.total || 100) ? s : worst, null);

  if (bestSubject) {
    doc.text(`Best Performance: ${bestSubject.subject?.name} (${bestSubject.total}%)`, 20, finalY + 36);
  }
  if (worstSubject) {
    doc.text(`Area for Improvement: ${worstSubject.subject?.name} (${worstSubject.total}%)`, 20, finalY + 44);
  }

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by IKONEX Academy Management System', 105, 285, { align: 'center' });
  doc.text(new Date().toLocaleDateString(), 105, 292, { align: 'center' });

  return doc;
}

// Generate class performance report
export async function generateClassReport(stream: any, students: any[]) {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(22);
  doc.setTextColor(0, 51, 102);
  doc.text('IKONEX ACADEMY', 105, 25, { align: 'center' });

  doc.setFontSize(16);
  doc.setTextColor(100, 100, 100);
  doc.text('Class Performance Report', 105, 38, { align: 'center' });

  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text(stream.name, 105, 50, { align: 'center' });

  doc.setDrawColor(0, 51, 102);
  doc.setLineWidth(1);
  doc.line(20, 55, 190, 55);

  // Calculate class statistics
  let totalMarks = 0;
  let totalScores = 0;
  const gradeCount = { A: 0, B: 0, C: 0, D: 0, E: 0, F: 0 };
  const subjectPerformance: any = {};

  const studentData = students.map(student => {
    const studentTotal = student.scores?.reduce((sum: number, s: any) => sum + s.total, 0) || 0;
    const studentAvg = student.scores?.length > 0 ? studentTotal / student.scores.length : 0;
    
    totalMarks += studentTotal;
    totalScores += student.scores?.length || 0;
    
    let grade = 'F';
    if (studentAvg >= 80) { grade = 'A'; gradeCount.A++; }
    else if (studentAvg >= 70) { grade = 'B'; gradeCount.B++; }
    else if (studentAvg >= 60) { grade = 'C'; gradeCount.C++; }
    else if (studentAvg >= 50) { grade = 'D'; gradeCount.D++; }
    else if (studentAvg >= 40) { grade = 'E'; gradeCount.E++; }
    else { gradeCount.F++; }

    // Track subject performance
    student.scores?.forEach((score: any) => {
      const subjectName = score.subject?.name;
      if (subjectName) {
        if (!subjectPerformance[subjectName]) {
          subjectPerformance[subjectName] = { total: 0, count: 0 };
        }
        subjectPerformance[subjectName].total += score.total;
        subjectPerformance[subjectName].count++;
      }
    });
    
    return [
      student.admissionNo,
      student.name,
      studentTotal.toString(),
      studentAvg.toFixed(2) + '%',
      grade
    ];
  }).sort((a, b) => parseFloat(b[3]) - parseFloat(a[3]));

  const classAverage = totalScores > 0 ? totalMarks / totalScores : 0;
  const passCount = gradeCount.A + gradeCount.B + gradeCount.C + gradeCount.D;
  const passRate = students.length > 0 ? (passCount / students.length) * 100 : 0;

  // Student performance table
  (doc as any).autoTable({
    startY: 65,
    head: [['Admission No', 'Student Name', 'Total Marks', 'Average', 'Grade']],
    body: studentData,
    theme: 'striped',
    headStyles: { fillColor: [0, 51, 102], textColor: 255, fontSize: 10 },
    bodyStyles: { fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 30 },
      1: { cellWidth: 50 },
      2: { cellWidth: 25, align: 'center' },
      3: { cellWidth: 25, align: 'center' },
      4: { cellWidth: 20, align: 'center' }
    }
  });

  const finalY = (doc as any).lastAutoTable.finalY + 15;

  // Class summary
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.text(`Total Students: ${students.length}`, 20, finalY);
  doc.text(`Class Average: ${classAverage.toFixed(2)}%`, 20, finalY + 8);
  doc.text(`Pass Rate: ${passRate.toFixed(2)}%`, 20, finalY + 16);
  doc.text(`Top Performer: ${studentData[0]?.[1] || 'N/A'}`, 20, finalY + 24);
  doc.text(`Lowest Performer: ${studentData[studentData.length - 1]?.[1] || 'N/A'}`, 20, finalY + 32);

  // Grade distribution
  const gradeY = finalY + 50;
  doc.setFontSize(11);
  doc.text('Grade Distribution:', 20, gradeY);
  
  let xPos = 20;
  const grades = ['A', 'B', 'C', 'D', 'E', 'F'];
  grades.forEach(grade => {
    const count = gradeCount[grade as keyof typeof gradeCount];
    const percentage = students.length > 0 ? (count / students.length) * 100 : 0;
    doc.text(`${grade}: ${count} (${percentage.toFixed(1)}%)`, xPos, gradeY + 8);
    xPos += 45;
  });

  // Subject performance
  const subjectY = gradeY + 25;
  doc.text('Subject Performance:', 20, subjectY);
  
  let yOffset = subjectY + 8;
  for (const [subject, data] of Object.entries(subjectPerformance)) {
    const avg = (data as any).total / (data as any).count;
    doc.text(`${subject}: ${avg.toFixed(2)}%`, 25, yOffset);
    yOffset += 6;
    
    if (yOffset > 270) break;
  }

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by IKONEX Academy Management System', 105, 285, { align: 'center' });
  doc.text(new Date().toLocaleDateString(), 105, 292, { align: 'center' });

  return doc;
}

// Generate subject analysis report
export async function generateSubjectReport(subject: any, scores: any[], students: any[]) {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(22);
  doc.setTextColor(0, 51, 102);
  doc.text('IKONEX ACADEMY', 105, 25, { align: 'center' });

  doc.setFontSize(16);
  doc.setTextColor(100, 100, 100);
  doc.text('Subject Performance Report', 105, 38, { align: 'center' });

  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text(subject.name, 105, 50, { align: 'center' });

  doc.setDrawColor(0, 51, 102);
  doc.setLineWidth(1);
  doc.line(20, 55, 190, 55);

  // Calculate subject statistics
  const totalScore = scores.reduce((sum, s) => sum + s.total, 0);
  const averageScore = scores.length > 0 ? totalScore / scores.length : 0;
  const highestScore = scores.length > 0 ? Math.max(...scores.map(s => s.total)) : 0;
  const lowestScore = scores.length > 0 ? Math.min(...scores.map(s => s.total)) : 0;
  
  const passCount = scores.filter(s => s.grade !== 'F').length;
  const passRate = scores.length > 0 ? (passCount / scores.length) * 100 : 0;
  
  const gradeDistribution = {
    A: scores.filter(s => s.total >= 80).length,
    B: scores.filter(s => s.total >= 70 && s.total < 80).length,
    C: scores.filter(s => s.total >= 60 && s.total < 70).length,
    D: scores.filter(s => s.total >= 50 && s.total < 60).length,
    E: scores.filter(s => s.total >= 40 && s.total < 50).length,
    F: scores.filter(s => s.total < 40).length
  };

  // Score distribution table
  const scoreRanges = [
    { range: '80-100', count: gradeDistribution.A, percentage: (gradeDistribution.A / scores.length) * 100 },
    { range: '70-79', count: gradeDistribution.B, percentage: (gradeDistribution.B / scores.length) * 100 },
    { range: '60-69', count: gradeDistribution.C, percentage: (gradeDistribution.C / scores.length) * 100 },
    { range: '50-59', count: gradeDistribution.D, percentage: (gradeDistribution.D / scores.length) * 100 },
    { range: '40-49', count: gradeDistribution.E, percentage: (gradeDistribution.E / scores.length) * 100 },
    { range: '0-39', count: gradeDistribution.F, percentage: (gradeDistribution.F / scores.length) * 100 }
  ];

  (doc as any).autoTable({
    startY: 65,
    head: [['Score Range', 'Number of Students', 'Percentage']],
    body: scoreRanges.map(s => [s.range, s.count.toString(), s.percentage.toFixed(1) + '%']),
    theme: 'striped',
    headStyles: { fillColor: [0, 51, 102], textColor: 255 },
    styles: { fontSize: 10 }
  });

  const finalY = (doc as any).lastAutoTable.finalY + 15;

  // Summary statistics
  doc.setFontSize(11);
  doc.text(`Total Students: ${students.length}`, 20, finalY);
  doc.text(`Students Examined: ${scores.length}`, 20, finalY + 8);
  doc.text(`Average Score: ${averageScore.toFixed(2)}%`, 20, finalY + 16);
  doc.text(`Highest Score: ${highestScore}%`, 20, finalY + 24);
  doc.text(`Lowest Score: ${lowestScore}%`, 20, finalY + 32);
  doc.text(`Pass Rate: ${passRate.toFixed(2)}%`, 20, finalY + 40);

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by IKONEX Academy Management System', 105, 285, { align: 'center' });
  doc.text(new Date().toLocaleDateString(), 105, 292, { align: 'center' });

  return doc;
}

// Generate transcript for a student (all terms/years)
export async function generateStudentTranscript(student: any, allScores: any[]) {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(22);
  doc.setTextColor(0, 51, 102);
  doc.text('IKONEX ACADEMY', 105, 25, { align: 'center' });

  doc.setFontSize(16);
  doc.setTextColor(100, 100, 100);
  doc.text('Academic Transcript', 105, 38, { align: 'center' });

  doc.setDrawColor(0, 51, 102);
  doc.setLineWidth(1);
  doc.line(20, 45, 190, 45);

  // Student Information
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.text(`Name: ${student.name}`, 20, 58);
  doc.text(`Admission No: ${student.admissionNo}`, 20, 66);
  doc.text(`Class: ${student.stream?.name || 'N/A'}`, 20, 74);

  // Group scores by term and year
  const groupedScores: any = {};
  allScores.forEach(score => {
    const key = `${score.term} ${score.year}`;
    if (!groupedScores[key]) {
      groupedScores[key] = [];
    }
    groupedScores[key].push(score);
  });

  let currentY = 85;
  
  for (const [period, periodScores] of Object.entries(groupedScores)) {
    const scoresArray = periodScores as any[];
    const termTotal = scoresArray.reduce((sum, s) => sum + s.total, 0);
    const termAverage = scoresArray.length > 0 ? termTotal / scoresArray.length : 0;
    
    let termGrade = 'F';
    if (termAverage >= 80) termGrade = 'A';
    else if (termAverage >= 70) termGrade = 'B';
    else if (termAverage >= 60) termGrade = 'C';
    else if (termAverage >= 50) termGrade = 'D';
    else if (termAverage >= 40) termGrade = 'E';
    
    (doc as any).autoTable({
      startY: currentY,
      head: [[period, 'CA', 'Exam', 'Total', 'Grade']],
      body: scoresArray.map(score => [
        score.subject?.name || 'N/A',
        score.caScore.toString(),
        score.examScore.toString(),
        score.total.toString(),
        score.grade || '-'
      ]),
      foot: [['', '', 'Total:', termTotal.toString(), ''],
             ['', '', 'Average:', termAverage.toFixed(2) + '%', termGrade]],
      theme: 'striped',
      headStyles: { fillColor: [0, 51, 102], textColor: 255, fontSize: 10 },
      footStyles: { fillColor: [240, 240, 240], textColor: 0, fontStyle: 'bold' }
    });
    
    currentY = (doc as any).lastAutoTable.finalY + 15;
  }

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by IKONEX Academy Management System', 105, 285, { align: 'center' });
  doc.text(new Date().toLocaleDateString(), 105, 292, { align: 'center' });

  return doc;
}